# This file is used as a way to control NUGUS teleportation.

# rotation: [x, y, z, rotation degree in radian]
#   where; x + y + z <= 1               // x: tilt
#                                       // y: nod
#                                       // z: spin

# translation: [x, y, z]
#   where; x = -5.4 to 5.4              // goal post to goal post
#          y = -3.8 to 3.8              // sidelines
#          z = 0.51                     // optimal nugus height

locations:
  - rotation: [1, 0, -0.991091, -1.53982]
    translation: [1.2, -3, 0.51]
  - rotation: [1, 0, -0.991091, -1.3]
    translation: [1.2, -3, 0.51]
  - rotation: [1, 0, -0.991091, -1.53982]
    translation: [1.2, -3, 0.51]