/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller.vehicle;

public class vehicleJNI {

  static {
    try {
      System.loadLibrary("vehicle");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. See the chapter on Dynamic Linking Problems in the SWIG Java documentation for help.\n" + e);
      System.exit(1);
    }
  }

  public final static native long new_Driver();
  public final static native long Driver_getDriverInstance();
  public final static native void delete_Driver(long jarg1);
  public final static native boolean Driver_isInitialisationPossible();
  public final static native int Driver_step(long jarg1, Driver jarg1_);
  public final static native void Driver_setSteeringAngle(long jarg1, Driver jarg1_, double jarg2);
  public final static native double Driver_getSteeringAngle(long jarg1, Driver jarg1_);
  public final static native void Driver_setCruisingSpeed(long jarg1, Driver jarg1_, double jarg2);
  public final static native double Driver_getTargetCruisingSpeed(long jarg1, Driver jarg1_);
  public final static native double Driver_getCurrentSpeed(long jarg1, Driver jarg1_);
  public final static native void Driver_setThrottle(long jarg1, Driver jarg1_, double jarg2);
  public final static native double Driver_getThrottle(long jarg1, Driver jarg1_);
  public final static native void Driver_setBrakeIntensity(long jarg1, Driver jarg1_, double jarg2);
  public final static native double Driver_getBrakeIntensity(long jarg1, Driver jarg1_);
  public final static native void Driver_setIndicator(long jarg1, Driver jarg1_, int jarg2);
  public final static native void Driver_setHazardFlashers(long jarg1, Driver jarg1_, boolean jarg2);
  public final static native int Driver_getIndicator(long jarg1, Driver jarg1_);
  public final static native boolean Driver_getHazardFlashers(long jarg1, Driver jarg1_);
  public final static native void Driver_setDippedBeams(long jarg1, Driver jarg1_, boolean jarg2);
  public final static native void Driver_setAntifogLights(long jarg1, Driver jarg1_, boolean jarg2);
  public final static native boolean Driver_getDippedBeams(long jarg1, Driver jarg1_);
  public final static native boolean Driver_getAntifogLights(long jarg1, Driver jarg1_);
  public final static native double Driver_getRpm(long jarg1, Driver jarg1_);
  public final static native int Driver_getGear(long jarg1, Driver jarg1_);
  public final static native void Driver_setGear(long jarg1, Driver jarg1_, int jarg2);
  public final static native int Driver_getGearNumber(long jarg1, Driver jarg1_);
  public final static native int Driver_getControlMode(long jarg1, Driver jarg1_);
  public final static native void Driver_setWiperMode(long jarg1, Driver jarg1_, int jarg2);
  public final static native int Driver_getWiperMode(long jarg1, Driver jarg1_);
  public final static native void Driver_setBrake(long jarg1, Driver jarg1_, double jarg2);
  public final static native void Driver_setWipersMode(long jarg1, Driver jarg1_, int jarg2);
  public final static native int Driver_getWipersMode(long jarg1, Driver jarg1_);
  public final static native long new_Car();
  public final static native void delete_Car(long jarg1);
  public final static native int Car_getType(long jarg1, Car jarg1_);
  public final static native int Car_getEngineType(long jarg1, Car jarg1_);
  public final static native void Car_setIndicatorPeriod(long jarg1, Car jarg1_, double jarg2);
  public final static native double Car_getIndicatorPeriod(long jarg1, Car jarg1_);
  public final static native boolean Car_getBackwardsLights(long jarg1, Car jarg1_);
  public final static native boolean Car_getBrakeLights(long jarg1, Car jarg1_);
  public final static native double Car_getTrackFront(long jarg1, Car jarg1_);
  public final static native double Car_getTrackRear(long jarg1, Car jarg1_);
  public final static native double Car_getWheelbase(long jarg1, Car jarg1_);
  public final static native double Car_getFrontWheelRadius(long jarg1, Car jarg1_);
  public final static native double Car_getRearWheelRadius(long jarg1, Car jarg1_);
  public final static native double Car_getWheelEncoder(long jarg1, Car jarg1_, int jarg2);
  public final static native double Car_getWheelSpeed(long jarg1, Car jarg1_, int jarg2);
  public final static native void Car_setLeftSteeringAngle(long jarg1, Car jarg1_, double jarg2);
  public final static native void Car_setRightSteeringAngle(long jarg1, Car jarg1_, double jarg2);
  public final static native double Car_getRightSteeringAngle(long jarg1, Car jarg1_);
  public final static native double Car_getLeftSteeringAngle(long jarg1, Car jarg1_);
  public final static native void Car_enableLimitedSlipDifferential(long jarg1, Car jarg1_, boolean jarg2);
  public final static native void Car_enableIndicatorAutoDisabling(long jarg1, Car jarg1_, boolean jarg2);
  public final static native long Driver_SWIGUpcast(long jarg1);
  public final static native long Car_SWIGUpcast(long jarg1);
}
