#AngleAxis rotations to spin robot around after teleporting to a location and
# gain a range of angles
rotations:
  -
    - 0
    - 1
    - 0
    - 0
  -
    - 0
    - 0
    - 1
    - 0.785398
  -
    - 0
    - 0
    - 1
    - 1.5708
  -
    - 0
    - 0
    - 1
    - 2.3562
  -
    - 0
    - 0
    - 1
    - -3.14159
  -
    - 0
    - 0
    - -1
    - 2.3562
  -
    - 0
    - 0
    - -1
    - 1.5708
  -
    - 0
    - 0
    - -1
    - 0.785398

min_distance: 0.5
z_height: 0.51

